/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author pirulo
 */
public class PantallaConfirmarAlgo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaConfirmarAlgo.class.getName());

    /**
     * Creates new form PantallaConfirmarAlgo
     */
    public PantallaConfirmarAlgo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        btnEleccionSi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEleccionNo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        taPadrePreguntas = new javax.swing.JScrollPane();
        taPregunta = new javax.swing.JTextArea();
        lblDebugEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 150));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEleccionSi.setBackground(new java.awt.Color(0, 102, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SI");

        javax.swing.GroupLayout btnEleccionSiLayout = new javax.swing.GroupLayout(btnEleccionSi);
        btnEleccionSi.setLayout(btnEleccionSiLayout);
        btnEleccionSiLayout.setHorizontalGroup(
            btnEleccionSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        btnEleccionSiLayout.setVerticalGroup(
            btnEleccionSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        fondo.add(btnEleccionSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, 40));

        btnEleccionNo.setBackground(new java.awt.Color(153, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NO");

        javax.swing.GroupLayout btnEleccionNoLayout = new javax.swing.GroupLayout(btnEleccionNo);
        btnEleccionNo.setLayout(btnEleccionNoLayout);
        btnEleccionNoLayout.setHorizontalGroup(
            btnEleccionNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEleccionNoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEleccionNoLayout.setVerticalGroup(
            btnEleccionNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        fondo.add(btnEleccionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 40));

        taPregunta.setColumns(20);
        taPregunta.setRows(5);
        taPadrePreguntas.setViewportView(taPregunta);

        fondo.add(taPadrePreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 420, 70));
        fondo.add(lblDebugEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEleccionNo;
    private javax.swing.JPanel btnEleccionSi;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDebugEstado;
    private javax.swing.JScrollPane taPadrePreguntas;
    private javax.swing.JTextArea taPregunta;
    // End of variables declaration//GEN-END:variables
}
