/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author pirulo
 */
public class PantallaBuscarContrasenia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaBuscarContrasenia.class.getName());

    /**
     * Creates new form PantallaBuscarContrasenia
     */
    public PantallaBuscarContrasenia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        scrollerListaContrasenias = new javax.swing.JScrollPane();
        listaContrasenias = new javax.swing.JList<>();
        btnVolverAtras = new javax.swing.JPanel();
        lblVolverAtras = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblIndicaciones = new javax.swing.JLabel();
        lblAclaraciones = new javax.swing.JLabel();
        tfBuscador = new javax.swing.JTextField();
        lblDebugEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollerListaContrasenias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 8));
        scrollerListaContrasenias.setAutoscrolls(true);

        listaContrasenias.setBackground(new java.awt.Color(255, 255, 204));
        listaContrasenias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseñas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 14))); // NOI18N
        listaContrasenias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sitio                            ||                           Nombre de la Cuenta                          ||                   Contraseña", "Item 2", "Item 3", "Item 4s", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4s", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4s", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4s", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4s", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4s", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4s", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaContrasenias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaContrasenias.setToolTipText("buen día");
        listaContrasenias.setAutoscrolls(false);
        listaContrasenias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrollerListaContrasenias.setViewportView(listaContrasenias);

        fondo.add(scrollerListaContrasenias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 755, 280));

        btnVolverAtras.setBackground(new java.awt.Color(102, 0, 0));
        btnVolverAtras.setForeground(new java.awt.Color(255, 255, 255));

        lblVolverAtras.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVolverAtras.setForeground(new java.awt.Color(204, 204, 204));
        lblVolverAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverAtras.setText("<== Volver Atras");

        javax.swing.GroupLayout btnVolverAtrasLayout = new javax.swing.GroupLayout(btnVolverAtras);
        btnVolverAtras.setLayout(btnVolverAtrasLayout);
        btnVolverAtrasLayout.setHorizontalGroup(
            btnVolverAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        btnVolverAtrasLayout.setVerticalGroup(
            btnVolverAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        fondo.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 70));

        lblTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblTitulo.setText("Buscar Contraseñas");
        fondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        lblIndicaciones.setText("Utilize la barra de búsqueda para buscar contraseñas por su sitio. ");
        fondo.add(lblIndicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lblAclaraciones.setText("Los datos ocultos se van a ver como x-x-x-x-x, para verlos entre en el modo de contraseñas ocultas");
        fondo.add(lblAclaraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        fondo.add(tfBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));
        fondo.add(lblDebugEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnVolverAtras;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel lblAclaraciones;
    private javax.swing.JLabel lblDebugEstado;
    private javax.swing.JLabel lblIndicaciones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolverAtras;
    private javax.swing.JList<String> listaContrasenias;
    private javax.swing.JScrollPane scrollerListaContrasenias;
    private javax.swing.JTextField tfBuscador;
    // End of variables declaration//GEN-END:variables
}
