/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author pirulo
 */
public class PantallaIngresarContrasenia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaIngresarContrasenia.class.getName());

    /**
     * Creates new form PantallaIngresarContrasenia
     */
    public PantallaIngresarContrasenia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pfContrasenia = new javax.swing.JPasswordField();
        btnVerificar = new javax.swing.JPanel();
        lblVerificar = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        lblDebugEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 150));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblTitulo.setText("Ingrese su contrasenia");
        fondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 6, -1, -1));

        pfContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondo.add(pfContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 46, 308, -1));

        btnVerificar.setBackground(new java.awt.Color(0, 102, 0));

        lblVerificar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVerificar.setForeground(new java.awt.Color(204, 204, 204));
        lblVerificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerificar.setText("Verificar");

        javax.swing.GroupLayout btnVerificarLayout = new javax.swing.GroupLayout(btnVerificar);
        btnVerificar.setLayout(btnVerificarLayout);
        btnVerificarLayout.setHorizontalGroup(
            btnVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        btnVerificarLayout.setVerticalGroup(
            btnVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        fondo.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        btnVolver.setBackground(new java.awt.Color(153, 0, 0));

        lblVolver.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVolver.setForeground(new java.awt.Color(204, 204, 204));
        lblVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolver.setText("Volver");

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        fondo.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        fondo.add(lblDebugEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnVerificar;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel lblDebugEstado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerificar;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPasswordField pfContrasenia;
    // End of variables declaration//GEN-END:variables
}
