/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author pirulo
 */
public class PantallaAgregarEditarCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaAgregarEditarCuenta.class.getName());

    /**
     * Creates new form PantallaAgregarCuenta
     */
    public PantallaAgregarEditarCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JPanel();
        lblVolverAtras = new javax.swing.JLabel();
        tfSitio = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblSitioIngresado = new javax.swing.JLabel();
        cboxSitioOculto = new javax.swing.JCheckBox();
        lblErrorSitio = new javax.swing.JLabel();
        tfNombreCuenta = new javax.swing.JTextField();
        lblNombreCuentaIngresado = new javax.swing.JLabel();
        cboxNombreCuentaOculto = new javax.swing.JCheckBox();
        lblErrorNombreCuenta = new javax.swing.JLabel();
        tfContrasenia = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        cboxContraseniaOculto = new javax.swing.JCheckBox();
        lblErrorContrasenia = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JPanel();
        lblConfirmar = new javax.swing.JLabel();
        lblDebugEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverAtras.setBackground(new java.awt.Color(102, 0, 0));
        btnVolverAtras.setForeground(new java.awt.Color(255, 255, 255));

        lblVolverAtras.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVolverAtras.setForeground(new java.awt.Color(204, 204, 204));
        lblVolverAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverAtras.setText("<== Volver Atras");

        javax.swing.GroupLayout btnVolverAtrasLayout = new javax.swing.GroupLayout(btnVolverAtras);
        btnVolverAtras.setLayout(btnVolverAtrasLayout);
        btnVolverAtrasLayout.setHorizontalGroup(
            btnVolverAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        btnVolverAtrasLayout.setVerticalGroup(
            btnVolverAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        fondo.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 70));
        fondo.add(tfSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 40));

        lblTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblTitulo.setText("Agregar Contrasenia");
        fondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lblSitioIngresado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSitioIngresado.setText("Sitio:");
        fondo.add(lblSitioIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        cboxSitioOculto.setText("Ocultar Sitio");
        cboxSitioOculto.addActionListener(this::cboxSitioOcultoActionPerformed);
        fondo.add(cboxSitioOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblErrorSitio.setForeground(new java.awt.Color(255, 51, 51));
        fondo.add(lblErrorSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        fondo.add(tfNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 290, 40));

        lblNombreCuentaIngresado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNombreCuentaIngresado.setText("Nombre de la Cuenta:");
        fondo.add(lblNombreCuentaIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        cboxNombreCuentaOculto.setText("Ocultar nombre de la cuenta");
        cboxNombreCuentaOculto.addActionListener(this::cboxNombreCuentaOcultoActionPerformed);
        fondo.add(cboxNombreCuentaOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        lblErrorNombreCuenta.setForeground(new java.awt.Color(255, 51, 51));
        fondo.add(lblErrorNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));
        fondo.add(tfContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 290, 40));

        lblContrasenia.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblContrasenia.setText("Contraseña:");
        fondo.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        cboxContraseniaOculto.setText("Ocultar Sitio");
        cboxContraseniaOculto.addActionListener(this::cboxContraseniaOcultoActionPerformed);
        fondo.add(cboxContraseniaOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        lblErrorContrasenia.setForeground(new java.awt.Color(255, 51, 51));
        fondo.add(lblErrorContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 0));

        lblConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        lblConfirmar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        lblConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmar.setText("Agregar nueva contraseña");

        javax.swing.GroupLayout btnConfirmarLayout = new javax.swing.GroupLayout(btnConfirmar);
        btnConfirmar.setLayout(btnConfirmarLayout);
        btnConfirmarLayout.setHorizontalGroup(
            btnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        btnConfirmarLayout.setVerticalGroup(
            btnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        fondo.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 400, 60));
        fondo.add(lblDebugEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxSitioOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxSitioOcultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxSitioOcultoActionPerformed

    private void cboxNombreCuentaOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxNombreCuentaOcultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxNombreCuentaOcultoActionPerformed

    private void cboxContraseniaOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxContraseniaOcultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxContraseniaOcultoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnConfirmar;
    private javax.swing.JPanel btnVolverAtras;
    private javax.swing.JCheckBox cboxContraseniaOculto;
    private javax.swing.JCheckBox cboxNombreCuentaOculto;
    private javax.swing.JCheckBox cboxSitioOculto;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblDebugEstado;
    private javax.swing.JLabel lblErrorContrasenia;
    private javax.swing.JLabel lblErrorNombreCuenta;
    private javax.swing.JLabel lblErrorSitio;
    private javax.swing.JLabel lblNombreCuentaIngresado;
    private javax.swing.JLabel lblSitioIngresado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolverAtras;
    private javax.swing.JTextField tfContrasenia;
    private javax.swing.JTextField tfNombreCuenta;
    private javax.swing.JTextField tfSitio;
    // End of variables declaration//GEN-END:variables
}
